server:
  port: 1217
  mode: release    # release, test

logging:
  level: warn
  file-path: ./logs/app.log
  file-max-size: 10 #10M
  max-history: 30
  compress: false
#  local-time: false
#  max-backups: 10
