server:
  port: 1217
  mode: release    # release, test

logging:
  level:
    root: warn
    com.gridvo.eagle: ${LOG_LEVEL:warn}
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: ${LOG_MAX_HISTORY:30}